Repository improbable-eng/grpc-web, pull requests merged in 2022-01, with the labels that each got.

#1066 updated documentation to accurately reflect the existing API for unary call aborting
  client/grpc-web/README.md
Labels: size/XS

#1070 Fix go mod tidy
  go.mod
  go.sum
Labels: size/S

#1069 [grpcweb/go] Allow Access-Control-Max-Age customization
  go/grpcweb/DOC.md
  go/grpcweb/options.go
  go/grpcweb/wrapper.go
  go/grpcweb/wrapper_test.go
Labels: size/M
