Repository improbable-eng/grpc-web, pull requests merged in 2022-03, with the labels that each got.

#1090 Bump prometheus/client_golang from v1.7.1 to v1.12.1
  go.mod
  go.sum
  integration_test/go/_proto/improbable/grpcweb/test/test.pb.go
  integration_test/go/testserver/testserver.go
Labels: size/XL

#1096 fix(websockets): fix websockets non root resources replace
  go/grpcweb/wrapper.go
Labels: size/XS

#1092 Limit parallelism of browser tests
  .circleci/config.yml
Labels: size/S
